### ISSUE TITLE
Remove login link from sticky menu bar

### ISSUE THREAD

**Issue by loreleileigh** [uwcirg/tb-mobile-app#4]
(Maybe this will already be taken care of when the menu bar is redone, or maybe it's just doing this because we haven't logged in :)) 
Login or signup link should not be visible once the user is actually logged in. 

Further questions about logging in generally - when does login expire? When browser is closed?
 And/or after a certain period? 
When login expires can we redirect user to startup signin page? App should not be usable without being logged in anyway~

**Comment by pmanko** [comment]
@loreleileigh Good questions - I'm working on the logging in/ authentication part now. It's a bit complicated, because were integrating the mPOWEr survey functionality. I'm going to close this issue (the login link is removed) and create a new Login/Logout/Authentication specific one, where I'll copy your questions.
