### ISSUE TITLE
Registration, Authentication, and Login Flow

### ISSUE THREAD

**Issue by pmanko** [uwcirg/tb-mobile-app#9]
## General questions about logging in
1. When does login expire? When browser is closed? And/or after a certain period?

2. When login expires can we redirect user to startup signin page?

**Comment by loreleileigh** [comment]
Looping in @sjiribarren - what are your thoughts here? :) 
Absent user data (e.g. do pts share their mobile phones? do they typically passlock phones? are mobile phones frequently stolen?) and so operating in an "average user" vacuum, it seems for maintaining a balance between convenience and security we could have login expire after closing the browser window or after, say, an hour of disuse? 
Agree that unauthenticated user should just go to the signup/login page and the login defaults to the Home screen~ 
On that note (and please feel free to move these comments somewhere else that makes more sense!) - the Home screen looks lovely! My two thoughts are: 1. Since we're using the icons, can we make the menu list left-justified to itself so that the icons line up (and if necessary/not difficult to do, it'd still be good to otherwise centre-justify to fulfil browser responsiveness)? 2. The alternating dark grey background should be slightly lighter, eh, maybe something like c9c9c9? (Feel free to let me know if there's a better/easier way to centralise style characteristics!) 
Wondering about a logout link and whether it's even necessary. Perhaps on signup tutorial (i.e. with help of care coordinator) can learn that closing browser = logout?

**Comment by sjiribarren** [comment]
There were a few patients who shared phones and a few were stolen.  I will find out if users have locked phones or other issues.  I think a 1hr log out is fine.  Maybe for future transition to a native app you would want to add the logout.  For not I am ok leaving it off and have it time out upon closing or 1 hr.  I agree with unauthenticated vs users directed.  And I agree coming along nicely!! Ya!

**Comment by thecalliopecrashed** [comment]
Migrating discussion to #60.
